### ISSUE TITLE
[Bug] CommandException: Unhandled exception executing command 'trade'

### ISSUE THREAD

**Issue by AlekseyVideman** [RyanA3/TradeUI#2]
[INFO]: Steve_golden_edition issued server command: /trade BillyJoe_Red
[ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'trade' in plugin TradeUI v1.1.5b
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-1.16.1.jar:git-Paper-44]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-1.16.1.jar:git-Paper-44]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[paper-1.16.1.jar:git-Paper-44]
at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[paper-1.16.1.jar:git-Paper-44]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719) ~[paper-1.16.1.jar:git-Paper-44]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[paper-1.16.1.jar:git-Paper-44]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[paper-1.16.1.jar:git-Paper-44]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[paper-1.16.1.jar:git-Paper-44]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[paper-1.16.1.jar:git-Paper-44]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[paper-1.16.1.jar:git-Paper-44]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[paper-1.16.1.jar:git-Paper-44]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[paper-1.16.1.jar:git-Paper-44]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[paper-1.16.1.jar:git-Paper-44]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[paper-1.16.1.jar:git-Paper-44]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[paper-1.16.1.jar:git-Paper-44]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[paper-1.16.1.jar:git-Paper-44]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[paper-1.16.1.jar:git-Paper-44]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[paper-1.16.1.jar:git-Paper-44]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_15_R1/Packet
at me.felnstaren.trade.request.TradeRequestHandler.addRequest(TradeRequestHandler.java:114) ~[?:?]
at me.felnstaren.trade.request.TradeRequestHandler.attemptSendRequest(TradeRequestHandler.java:108) ~[?:?]
at me.felnstaren.command.trade.player.TradePlayerArgument$1.handle(TradePlayerArgument.java:31) ~[?:?]
at me.felnstaren.command.CommandContinuator.stub(CommandContinuator.java:57) ~[?:?]
at me.felnstaren.command.CommandContinuator.forward(CommandContinuator.java:25) ~[?:?]
at me.felnstaren.command.SubArgument.handle(SubArgument.java:20) ~[?:?]
at me.felnstaren.command.CommandContinuator.forward(CommandContinuator.java:32) ~[?:?]
at me.felnstaren.command.trade.TradeMaster.handle(TradeMaster.java:51) ~[?:?]
at me.felnstaren.command.MasterCommand.onCommand(MasterCommand.java:26) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-1.16.1.jar:git-Paper-44]
... 18 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_15_R1.Packet
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[paper-1.16.1.jar:git-Paper-44]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[paper-1.16.1.jar:git-Paper-44]
at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
at me.felnstaren.trade.request.TradeRequestHandler.addRequest(TradeRequestHandler.java:114) ~[?:?]
at me.felnstaren.trade.request.TradeRequestHandler.attemptSendRequest(TradeRequestHandler.java:108) ~[?:?]
at me.felnstaren.command.trade.player.TradePlayerArgument$1.handle(TradePlayerArgument.java:31) ~[?:?]
at me.felnstaren.command.CommandContinuator.stub(CommandContinuator.java:57) ~[?:?]
at me.felnstaren.command.CommandContinuator.forward(CommandContinuator.java:25) ~[?:?]
at me.felnstaren.command.SubArgument.handle(SubArgument.java:20) ~[?:?]
at me.felnstaren.command.CommandContinuator.forward(CommandContinuator.java:32) ~[?:?]
at me.felnstaren.command.trade.TradeMaster.handle(TradeMaster.java:51) ~[?:?]
at me.felnstaren.command.MasterCommand.onCommand(MasterCommand.java:26) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-1.16.1.jar:git-Paper-44]
... 18 more 

Server core, version: Paper, 1.16.1
TradeUI version: 1.1.5b

**Comment by RyanA3** [comment]
TradeUI does not support 1.16+ versions of Minecraft
I'll be adding support for 1.16 in the near future

**Comment by RyanA3** [comment]
If you want to use TradeUI for 1.16+ right now, I believe setting 'use-commands' to false in the config will disable the clickable text, which is causing the issue in 1.16, however it will also require players to shift right click each other instead of using commands.

**Comment by AlekseyVideman** [comment]
Ok, thanks!
